### ISSUE TITLE
2018 refactoring proposal

### ISSUE THREAD

**Issue by omnivion** [CMSgov/qpp-conversion-tool#747]
See QPPCT-889

# Change converter endpoint response
Instead of just returning the qpp json, return the following object:
`
{
    "qpp": {
        // the qpp json in object form
    },
    "warnings": [
        {
            "code": 10,
            "message": "Blah blah something in your submission was odd but we did our best blah blah",
            "references": [
                "(link to the IG if applicable)",
                "(another link to the IG if applicable)"
            ]
        }
    ]
}
`

# Create StandardErrorCodes and StandardWarnings enums
They should implement ErrorCode/Warning interfaces, and contain general converter errors, such as malformed XML, missing encoder, or an unexpected error.

# Refactor data-specific error codes / warnings into date-based packages
Move error codes such as NPI_TIN_COMBINATION_MISSING_CLINICAL_DOCUMENT (error code 46) into their own date-based package, for example `gov.cms.qpp.conversion.model.error.nov2018jan2019.ErrorCode`. Also change the numeric code to include the date; such as `nov2018jan2019-46` or `09201801201946`. These should be further linked to a full list of all error codes, to facilitate the pipeline, explained in the next two sections.

# Change error code format to use named rather than numeric parameters
In the current format, placeholders in a message are replaced by the parameter passed in a numeric way. For example, in `Hello (your name)! My name is (my name).`, the placeholders `(your name)` and `(my name)` when passed parameters `1: "George", 2: "John"`, would be replaced in the message to make `Hello George! My name is John.`. My proposal would have the same outcome, but a different way of achieving it by replacing the numeric parameters with readable names. The passed parameters would become `your name: "George", my name: "John"`. If the message requires a parameter that is not given, an error should be thrown. This system has two benefits: readability, and facilitation of a pipeline mechanism; when calling an error in an encoder/decoder/validator, you'd reference the shared error code between all years mentioned in the previous item, passing in all required variables for that shared error code's date-based implementor.

# Create encoder/decoder/validation date based pipeline
To make supporting a new submission date range easier, we should only have to implement a diff of the changes between the current supported date range's spec and the new spec. If no changes are made to an encoder/decoder/validator, we don't want to have to repeat the same code.

**Comment by saquino0827** [comment]
Converter Endpoint Response:
I like the idea of returning an object containing everything we need. There will be work involving other teams for the UI as well as changes to our own endpoints when we submit validation to the submission validation api. I do not know a use case for `references` off the top of my head.

Create StandardErrorCodes and StandardWarnings enums:
This looks good.

Refactor data-specific error codes / warnings into date-based packages:
I feel like this also falls under `Create encoder/decoder/validation date based pipeline` as we would want to keep all code we reuse in one area as well as separate a different yearly validation. But I ultimately like this idea.

Change error code format to use named rather than numeric parameters:
This is a nice refactor but I do not believe it's required. I guess it depends if we're time constrained to do this or not.

**Comment by omnivion** [comment]
@saquino0827 references is so we don't have to link to the IG in the error message. It can also be used by the UI to separate reference links from the message, kind of like how it works on wikipedia.

**Comment by JeffBJr56** [comment]
After reading through the proposals all of them seem to be fine for HIVVS. The only thing that would need to be put into consideration on our end is added overhead this creates due to the refactoring of test cases for these new changes. So test case creation for new ones may slow down as a result. Besides that all of the proposed changes seem to be within the capabilities of our testing framework.

**Comment by sfradkin** [comment]
I like this proposal.  Let's add stories to the backlog.
